---
- name: Install and configure PowerDNS with Geo-routing
  hosts: "{{ 'app2' if DEPLOY_ENV == 'staging' else 'app' }}"
  become: yes
  vars_files:
    - vars.yaml

  tasks:
    - name: Create apt keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download PowerDNS repository key
      ansible.builtin.get_url:
        url: "https://repo.powerdns.com/FD380FBB-pub.asc"
        dest: /tmp/powerdns-key.asc
        mode: "0644"

    - name: Add PowerDNS repository key to keyring
      ansible.builtin.shell:
        cmd: gpg --dearmor < /tmp/powerdns-key.asc > /etc/apt/keyrings/powerdns.gpg
        creates: /etc/apt/keyrings/powerdns.gpg

    - name: Add PowerDNS repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/powerdns.gpg] http://repo.powerdns.com/ubuntu {{ ansible_distribution_release }}-auth-{{ powerdns.auth_version }} main"
        state: present
        filename: powerdns

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Copy Resolve configuration file
      ansible.builtin.copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"

    - name: Disable and stop systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Install required packages
      ansible.builtin.package:
        name:
          - pdns-server
          - pdns-backend-sqlite3
          - pdns-backend-geoip
          - python3
          - logrotate
          - nginx
          - wget
          - libgeoip1
          - libmaxminddb0
          - mmdb-bin
          - geoipupdate
          - sqlite3
        state: present

    - name: register state of /etc/apt/sources.list.d/nodesource.list
      stat:
        path: /etc/apt/sources.list.d/nodesource.list
      register: nodesource_path

    - name: Download Node.js 22.x setup script
      ansible.builtin.get_url:
        url: "https://deb.nodesource.com/setup_22.x"
        dest: /tmp/nodejs_setup.sh
        mode: "0755"
      when: not nodesource_path.stat.exists

    - name: Install Node.js 22.x repository
      ansible.builtin.shell:
        cmd: /tmp/nodejs_setup.sh
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js
      apt:
        name: nodejs
        state: latest

    # GeoIP Database Setup with MaxMind
    - name: Create GeoIP directory
      ansible.builtin.file:
        path: /usr/share/GeoIP
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create GeoIP configuration from template
      ansible.builtin.template:
        src: templates/GeoIP.conf.j2
        dest: /etc/GeoIP.conf
        owner: root
        group: root
        mode: "0600"

    - name: Run initial GeoIP database update
      command: /usr/bin/geoipupdate
      register: geoip_update
      failed_when: geoip_update.rc != 0

    - name: Verify GeoIP databases exist
      ansible.builtin.stat:
        path: "{{ item }}"
      with_items:
        - /usr/share/GeoIP/GeoLite2-City.mmdb
        - /usr/share/GeoIP/GeoLite2-Country.mmdb
      register: geoip_files
      failed_when: not geoip_files.stat.exists

    - name: Set up weekly GeoIP database updates
      ansible.builtin.cron:
        name: "Update GeoIP databases"
        user: root
        job: "/usr/bin/geoipupdate"
        weekday: "0"
        hour: "3"
        minute: "0"

    # Existing health checker setup
    - name: Create the destination directory
      file:
        path: /opt/healthchecker/src
        state: directory
      become: yes

    - name: Sync application files
      synchronize:
        src: src/
        dest: /opt/healthchecker/src
        recursive: yes

    - name: Template the health route
      ansible.builtin.template:
        src: templates/health.js.j2
        dest: /opt/healthchecker/src/routes/health.js
        owner: root
        group: root
        mode: 0777
      vars:
        subdomain: "{{ 'app2' if DEPLOY_ENV == 'staging' else 'app' }}"

    - name: Install npm dependencies for healthchecker
      npm:
        path: /opt/healthchecker/src
        state: present

    - name: Create systemd service for healthchecker
      ansible.builtin.template:
        src: templates/healthchecker.service.j2
        dest: /etc/systemd/system/healthchecker.service
        owner: root
        group: root
        mode: "0644"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable healthchecker service
      ansible.builtin.systemd:
        name: healthchecker
        state: started
        enabled: yes

    # PowerDNS configuration
    - name: Create PowerDNS zones directory
      ansible.builtin.file:
        path: /etc/powerdns/zones
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy PowerDNS main configuration file
      ansible.builtin.template:
        src: templates/pdns.conf.j2
        dest: /etc/powerdns/pdns.conf
        owner: root
        group: root
        mode: "0644"
        backup: yes

    # SQLite3 backend database setup
    - name: Create PowerDNS database directory
      ansible.builtin.file:
        path: /var/lib/powerdns
        state: directory
        owner: pdns
        group: pdns
        mode: "0755"

    - name: Check if PowerDNS database exists
      ansible.builtin.stat:
        path: /var/lib/powerdns/pdns.sqlite3
      register: pdns_db_stat

    - name: Initialize PowerDNS SQLite schema
      ansible.builtin.shell: |
        sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/pdns-backend-sqlite3/schema/schema.sqlite3.sql
        chown pdns:pdns /var/lib/powerdns/pdns.sqlite3
        chmod 640 /var/lib/powerdns/pdns.sqlite3
      when: not pdns_db_stat.stat.exists

    - name: Template named.conf for zone2sql conversion
      ansible.builtin.template:
        src: templates/named.conf.j2
        dest: /etc/powerdns/named.conf
        owner: root
        group: root
        mode: "0644"

    # Master/Slave replication setup with SQLite3 backend
    # TSIG keys are now stored in the database, not in separate files

    - name: Set environment for TSIG key selection
      ansible.builtin.set_fact:
        env: "{{ 'staging' if DEPLOY_ENV == 'staging' else 'production' }}"

    - name: Generate TSIG key for zone transfers if not set
      ansible.builtin.set_fact:
        tsig: "{{ tsig | default({}) | combine({env: {'zone_transfer_key': lookup('pipe', 'openssl rand -base64 48')}}, recursive=True) }}"
      when: tsig[env].zone_transfer_key | default('') in ['', 'REPLACE_WITH_STAGING_KEY', 'REPLACE_WITH_PRODUCTION_KEY']
      run_once: true

    # TSIG keys are now managed through SQLite3 backend via pdnsutil
    # The old file-based TSIG configuration is no longer needed

    - name: Copy zone file for geo-routing (production)
      ansible.builtin.copy:
        src: zones/cdn-geo.runonflux.io.zone
        dest: /etc/powerdns/zones/cdn-geo.runonflux.io.zone
        owner: root
        group: root
        mode: "0644"
      when: DEPLOY_ENV == 'production'

    - name: Copy zone file for geo-routing (staging)
      ansible.builtin.copy:
        src: zones/cdn-geodev.runonflux.io.zone
        dest: /etc/powerdns/zones/cdn-geodev.runonflux.io.zone
        owner: root
        group: root
        mode: "0644"
      when: DEPLOY_ENV == 'staging'

    - name: Copy zone file for app routing (production)
      ansible.builtin.copy:
        src: zones/app.runonflux.io.zone
        dest: /etc/powerdns/zones/app.runonflux.io.zone
        owner: root
        group: root
        mode: "0644"
      when: DEPLOY_ENV == 'production'

    - name: Copy zone file for app routing (staging)
      ansible.builtin.copy:
        src: zones/app2.runonflux.io.zone
        dest: /etc/powerdns/zones/app2.runonflux.io.zone
        owner: root
        group: root
        mode: "0644"
      when: DEPLOY_ENV == 'staging'

    # Zone migration from BIND to SQLite3 using zone2sql
    - name: Check if zones are already imported
      ansible.builtin.shell: |
        sqlite3 /var/lib/powerdns/pdns.sqlite3 "SELECT COUNT(*) FROM domains;"
      register: zone_count
      changed_when: false

    - name: Import zones from BIND files to SQLite database
      ansible.builtin.shell: |
        zone2sql --named-conf=/etc/powerdns/named.conf --gsqlite | sqlite3 /var/lib/powerdns/pdns.sqlite3
      when: zone_count.stdout | int == 0


    - name: Optimize database after zone import and fixes
      ansible.builtin.shell: |
        echo "ANALYZE;" | sqlite3 /var/lib/powerdns/pdns.sqlite3
      when: zone_count.stdout | int == 0

    # TSIG key configuration for SQLite3 backend
    - name: Check if TSIG key exists
      ansible.builtin.shell: |
        pdnsutil list-tsig-keys | grep "zone-transfer" || true
      register: tsig_key_exists
      changed_when: false

    - name: Import TSIG key for zone transfers
      ansible.builtin.shell: |
        pdnsutil import-tsig-key zone-transfer hmac-sha256 "{{ powerdns[env].tsig_zone_transfer_key }}"
      when: "'zone-transfer' not in tsig_key_exists.stdout"

    - name: Configure TSIG metadata for domains
      ansible.builtin.shell: |
        current=$(pdnsutil get-meta "{{ item }}" TSIG-ALLOW-AXFR 2>/dev/null || echo "")
        if [[ "$current" != *"zone-transfer"* ]]; then
          pdnsutil set-meta "{{ item }}" TSIG-ALLOW-AXFR zone-transfer
          echo "CHANGED"
        else
          echo "ALREADY_SET"
        fi
      loop: "{{ powerdns[env].zones }}"
      register: tsig_meta_result
      changed_when: "'CHANGED' in tsig_meta_result.stdout"
      when: pdns_role == 'master'

    - name: Configure SOA-EDIT-API for certbot compatibility
      ansible.builtin.shell: |
        current=$(pdnsutil get-meta "{{ item }}" SOA-EDIT-API 2>/dev/null || echo "")
        if [ "$current" != "INCREMENT" ]; then
          pdnsutil set-meta "{{ item }}" SOA-EDIT-API INCREMENT
          echo "CHANGED"
        else
          echo "ALREADY_SET"
        fi
      loop: "{{ powerdns[env].zones }}"
      register: soa_edit_result
      changed_when: "'CHANGED' in soa_edit_result.stdout"
      when: pdns_role == 'master'

    # Scripts directory setup
    - name: Ensure /opt/pdns/scripts directory exists
      ansible.builtin.file:
        path: /opt/pdns/scripts
        state: directory
        owner: root
        group: root
        mode: 0755

    # Note: Variables and pipe backend script no longer needed
    # App routing is now handled by Lua scripts in zone files

    - name: Copy Lua geo-routing script
      ansible.builtin.copy:
        src: scripts/geo_routing.lua
        dest: /opt/pdns/scripts/geo_routing.lua
        owner: root
        group: root
        mode: "0644"

    - name: Copy Lua app-routing script
      ansible.builtin.copy:
        src: scripts/app_routing.lua
        dest: /opt/pdns/scripts/app_routing.lua
        owner: root
        group: root
        mode: "0644"

    # Logrotate configuration
    - name: Copy PowerDNS logrotate configuration
      ansible.builtin.copy:
        src: pdns_logrotate.conf
        dest: /etc/logrotate.d/pdns
        owner: root
        group: root
        mode: "0644"

    - name: Set DEPLOY_ENV environment variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: "^DEPLOY_ENV="
        line: "DEPLOY_ENV={{ DEPLOY_ENV }}"
        state: present

    # Service management
    - name: Validate PowerDNS configuration
      command: pdns_server --config=check
      register: config_check
      failed_when: config_check.rc != 0
      changed_when: false

    - name: Restart PowerDNS service
      ansible.builtin.systemd:
        name: pdns
        state: restarted
        enabled: yes
      when: config_check.rc == 0

    - name: Ensure logrotate runs daily
      ansible.builtin.cron:
        name: "logrotate"
        user: "root"
        job: "/usr/sbin/logrotate /etc/logrotate.conf"
        day: "*"
        hour: "0"
        minute: "0"

    # Post-deployment verification
    - name: Wait for PowerDNS to start
      wait_for:
        port: 53
        host: 127.0.0.1
        delay: 5
        timeout: 30

    - name: Test DNS resolution for geo-routing domain
      command: dig @127.0.0.1 cdn-geo.runonflux.io A +short
      register: geo_dns_test
      retries: 3
      delay: 5
      until: geo_dns_test.rc == 0
      changed_when: false

    - name: Test DNS resolution for app routing (production)
      command: dig @127.0.0.1 test.app.runonflux.io CNAME +short
      register: app_dns_test
      retries: 3
      delay: 5
      until: app_dns_test.rc == 0
      changed_when: false

    # Master/Slave replication validation
    - name: Test zone transfer from master (slave servers only)
      command: dig @{{ ansible_default_ipv4.address }} {{ 'cdn-geodev.runonflux.io' if DEPLOY_ENV == 'staging' else 'cdn-geo.runonflux.io' }} AXFR
      register: axfr_test
      retries: 3
      delay: 10
      until: axfr_test.rc == 0
      changed_when: false
      when: pdns_role|default('slave') == 'slave'

    - name: Validate PowerDNS database exists and is accessible
      ansible.builtin.stat:
        path: /var/lib/powerdns/pdns.sqlite3
      register: pdns_db_check
      failed_when: not pdns_db_check.stat.exists
      when: pdns_role == 'master'

    - name: Test DNS update capability on master servers
      shell: |
        pdnsutil list-zone {{ 'cdn-geodev.runonflux.io' if DEPLOY_ENV == 'staging' else 'cdn-geo.runonflux.io' }}
      register: key_list_test
      changed_when: false
      when: pdns_role == 'master'


    - name: Test DNS resolution for app routing (staging)
      command: dig @127.0.0.1 test.app2.runonflux.io CNAME +short
      register: app2_dns_test
      retries: 3
      delay: 5
      until: app2_dns_test.rc == 0
      changed_when: false
      when: DEPLOY_ENV == 'staging'

    - name: Display DNS test results
      debug:
        msg: |
          Geo-routing test: {{ geo_dns_test.stdout }}
          App routing (prod) test: {{ app_dns_test.stdout }}
          App routing (staging) test: {{ app2_dns_test.stdout | default('N/A - prod environment') }}
