---
- name: Install and configure PowerDNS
  hosts: "{{ 'app2' if DEPLOY_ENV == 'staging' else 'app' }}"
  become: yes

  tasks:
    - name: Add PowerDNS repository key
      ansible.builtin.apt_key:
        url: "https://repo.powerdns.com/FD380FBB-pub.asc"
        state: present

    - name: Add PowerDNS repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://repo.powerdns.com/ubuntu {{ ansible_distribution_release }}-auth-{{ pdns_auth_version }} main"
        state: present
      vars:
        pdns_auth_version: "48"
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /etc/resolv.conf
  
    - name: Copy Resolve configuration file
      ansible.builtin.copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
    
    - name: Disable and stop systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Install required packages
      ansible.builtin.package:
        name:
          - pdns-server
          - pdns-backend-pipe
          - python3
          - logrotate
        state: present

    - name: Copy PowerDNS configuration file
      ansible.builtin.template:
        src: pdns.conf.j2
        dest: /etc/powerdns/pdns.conf
        owner: root
        group: root
        mode: '0644'
      vars:
        subdomain: "{{ 'app2' if DEPLOY_ENV == 'staging' else 'app' }}"

    - name: Ensure /opt/pdns/scripts directory exists
      ansible.builtin.file:
        path: /opt/pdns/scripts
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy multiple files to remote server
      ansible.builtin.copy:
        src: scripts/pdns_pipe_backend.py
        dest: /opt/pdns/scripts/pdns_pipe_backend.py
        owner: root
        group: root
        mode: 0777

    - name: Copy PowerDNS logrotate configuration
      ansible.builtin.copy:
        src: pdns_logrotate.conf
        dest: /etc/logrotate.d/pdns
        owner: root
        group: root
        mode: '0644'

    - name: Set DEPLOY_ENV environment variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^DEPLOY_ENV='
        line: "DEPLOY_ENV={{ DEPLOY_ENV }}"
        state: present

    - name: Restart PowerDNS service
      ansible.builtin.systemd:
        name: pdns
        state: restarted
        enabled: yes

    - name: Ensure logrotate runs daily
      ansible.builtin.cron:
        name: "logrotate"
        user: "root"
        job: "/usr/sbin/logrotate /etc/logrotate.conf"
        day: "*"
        hour: "0"
        minute: "0"